### ISSUE TITLE
Inditási rendszerüzenet

### ISSUE THREAD

**Issue by KoToITKft** [koto-it-kft/REDLine#1]
Az alkalmazás indításánál megjelenik egy Rendszer üzenet, hogy „Ön nem a legfrissebb programverziót használja” Ezt akkor is kiírja, ha a legfrissebb verziót töltjük le és úgy indítjuk a programot. (ez így most hibának tűnik).

**Comment by KoToITKft** [comment]
Nem hiba. RedlineConfig.xml-ben kell majd beállítani. Ez direkt volt most megnövelve.

**Comment by dobaizsolt** [comment]
Írd át, töltsd fel és jó lesz
