### ISSUE TITLE
AdHoc eltérés bejelentő felület: GPS mező maszkolása

### ISSUE THREAD

**Issue by KoToITKft** [koto-it-kft/REDLine#11]
A GPS mező, ha nincs automata kitöltés, akkor akár szabadon is lehet írni, azonban itt nem csak számokat fogad el a rendszer hanem betűket is. Esetleg érdemes maszkolni a mezőt.

**Comment by KoToITKft** [comment]
Fejlesztés

**Comment by dobaizsolt** [comment]
nem kell
