### ISSUE TITLE
Tematikus ellenőrzés előkészítése felület: SEPLAND/MISZ keresés

### ISSUE THREAD

**Issue by KoToITKft** [koto-it-kft/REDLine#14]
Ha a SEPLAND vagy MISZ azonosító ablakban csak pár kezdő karaktert gépelünk, akkor a keresésnél hozza fel az összes lehetséges találatot, ne csak az egzakt találatot!

**Comment by KoToITKft** [comment]
Fejlesztés. Ezt egy kicsit bővebben át kell beszélni, hogy mi is történjen. És honnan jönne az infó pár karakter alapján? Milyen szervízt kellene meghívni? És mit ad vissza? Usernek mit mutatunk meg? Mi történik utána ha megmutatunk valamit?

**Comment by dobaizsolt** [comment]
ez le lett szavazva
