### ISSUE TITLE
Tematikus ellenőrzés előkészítése felület: cim és leírás mező kitöltése

### ISSUE THREAD

**Issue by KoToITKft** [koto-it-kft/REDLine#15]
Ha egy SEPLAND számot beírok és rákeresek, akkor a cím és leírás mezőknek ki kellene töltődnie, hogy a lássuk valóban azt a munkát akarom-e ellenőrizni. Jelenleg pl a cs-11413 munkára keresésnél csak azt írja, ki, hogy „A megadott sepland azonosító mappa 4db dokumentumot tartalmaz” 
V. Bálint elvileg már átadta azt a lehetőséget, amivel ez megoldható.

**Comment by KoToITKft** [comment]
Fejlesztés. Nem tudok róla mit kellene hívni.

**Comment by KoToITKft** [comment]
Még nem kaptuk meg a V. Bálint által ígért webszervízt.

**Comment by dobaizsolt** [comment]
működik
