### ISSUE TITLE
Tematikus ellenőrzés felület: új számláló a munkákhoz

### ISSUE THREAD

**Issue by KoToITKft** [koto-it-kft/REDLine#17]
Amikor a jobbra-balra nyilakkal lépkedünk a felvett hibáknál, akkor nem látszik, hogy hol tartunk a sorban, hiszen akár biankó munkát is fel lehet venni.
Kellene még egy olyan számláló, mint a hibaablaknál.  
>>  Munka: 12/7 >> vagyis a 7. munka a 12-ből.

**Comment by KoToITKft** [comment]
Fejlesztés.

**Comment by dobaizsolt** [comment]
1.3 verzióban
