### ISSUE TITLE
Jegyzőkönyvek: Tematikus esetén

### ISSUE THREAD

**Issue by KoToITKft** [koto-it-kft/REDLine#26]
Sajnos itt nem teljesen úgy valósul meg a jegyzőkönyvkészítés, mint ahogyan kellene.
Minta példa:
![kép](https://user-images.githubusercontent.com/49682022/74199650-07884380-4c65-11ea-96f9-18377975d779.png)

Ebben az esetben összesen 3db jegyzőkönyvnek kell előállnia a folyamat végén.
:fleur_de_lis:	Megvalósulási_dok_hibajegyzőkönyv.PDF
•	1.munka Text1 hiba		(…+ mellékletek)
•	1.munka Text2 hiba		(…+ mellékletek)

:fleur_de_lis:	EEGIS_átvezetés_hiba_jegyzőkönyv.PDF
•	1.munka Text1 hiba		(…+ mellékletek)
•	1.munka Text3 hiba		(…+ mellékletek)

:fleur_de_lis:	Alaptérképi_hiba_jegyzőkönyv.PDF
•	1.munka Text1 hiba		(…+ mellékletek)
•	1.munka Text4 hiba		(…+ mellékletek)

Összesített jegyzőkönyv is készülhet akár, de azt az elektronikus rendszerben nem lehet felcsatolni sehova, csak a külön szálazott jegyzőkönyveket. Más az út, máshova mennek.

**Comment by KoToITKft** [comment]
Ellenőrzöm. Ha hiba javítom

**Comment by dobaizsolt** [comment]
Javítottam. 1.2-es verzióban is hibás?

**Comment by KoToITKft** [comment]
Ott szerintem még nem tesztelték.
Vagy tesztelték, de nem hiba már. Lezárom.
