### ISSUE TITLE
Mentés a terepi eszközre -Adhoc esetén

### ISSUE THREAD

**Issue by KoToITKft** [koto-it-kft/REDLine#27]
Elkészül. Az normális, hogy az alkatrészek nem jelennek meg az adott mappában? (fotók, hangfile)

**Comment by KoToITKft** [comment]
Igen. Semmi nem mentődik a vinyóra. Ha most esetleg valami mentődik a tesztidőszak miatt van. Kikapcsolom majd, hogy ne mentődjön.

**Comment by dobaizsolt** [comment]
Eszközre semmit nem mentünk
