### ISSUE TITLE
Importálás a DOKOS-ba: TEMATIKUS esetén

### ISSUE THREAD

**Issue by KoToITKft** [koto-it-kft/REDLine#30]
Hiába látszik a 3-as programválasztó felületen, hogy van wifi kapcsolat, a DOKOS felületén nem látszik az új mappa a jegyzőkönyv tartalmával, de az is igaz, hogy a korábbi jegyzőkönyvek megjelennek. Kérdés, hogy mikor vagy milyen feltételek mellett másolódik fel a jegyzőkönyv a DOKOS-ba?

**Comment by KoToITKft** [comment]
DOKOS-ba egy background task másol. Jogosultság rendben van? Logok mentek fel? Mit mutatnak?

**Comment by dobaizsolt** [comment]
Nem RedLine hiba.
