### ISSUE TITLE
AdHoc eltérés bejelentő felület: bejelentő neve

### ISSUE THREAD

**Issue by KoToITKft** [koto-it-kft/REDLine#7]
A Bejelentő neve mezőben a mobil eszközön a user teljes neve legyen kiírva, az elkészült jegyzőkönyvben pedig a teljes név + (windows név) formáció az olvashatóság és az egyértelmű azonosíthatóság miatt.

**Comment by KoToITKft** [comment]
Fejleszteni kell, mert nem tudunk kiolvasni teljes nevet. Le kell küldeni Ranker.xml-ben, és akkor tudjuk kezelni továbbiakban.

**Comment by dobaizsolt** [comment]
Kiolvasom Windowsból. Kész
