### ISSUE TITLE
AdHoc eltérés bejelentő felület: képernyő méretezés

### ISSUE THREAD

**Issue by KoToITKft** [koto-it-kft/REDLine#8]
A felületre is kellene egy tálcára letevő és egy teljes képernyős gomb, gondolva az idősebb szerelőkre is. A teljes képernyős módnál kérdés, hogy megoldható-e a nagyobb karakter, vagy szellősebb képernyő.

**Comment by KoToITKft** [comment]
Fejlesztés

**Comment by dobaizsolt** [comment]
nem kell
